# BL40A2010 Introduction to IoT-Based Systems

## Assignment 6, 18.12.2024

### Author: Jesse Peltola

In [1]:
! pip install nashpy


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


**Prisoner's dilemma** is a standard example of a game analyzed in game theory that shows why two completely rational individuals might not cooperate, even if it appears that it is in their best interests to do so. It was originally framed by Merrill Flood and Melvin Dresher while working at RAND in 1950. Albert W. Tucker formalized the game with prison sentence rewards and named it "prisoner's dilemma", presenting it as follows:

"Two members of a criminal gang are arrested and imprisoned. Each prisoner is in solitary confinement with no means of communicating with the other. The prosecutors lack sufficient evidence to convict the pair on the principal charge, but they have enough to convict both on a lesser charge. Simultaneously, the prosecutors offer each prisoner a bargain. Each prisoner is given the opportunity either to betray the other by testifying that the other committed the crime, or to cooperate with the other by remaining silent. The possible outcomes are:

- If A and B each betray the other (not-cooperating to each other), each of them serves $z$ years in prison (payoff of $-z$)
- If A betrays B (not-cooperating with B) but B remains silent (cooperating with A), A will serve $y$ years in prison (payoff $-y$) and B will serve $w$ years  (payoff of $-w$).
- If B betrays A (not-cooperating with A) but A remains silent (cooperating with B), B will serve $y$ years in prison (payoff $-y$) and A will serve $w$ years  (payoff of $-w$).
- If A and B both remain silent, both of them will serve $x$ years in prison (payoff of $-x$)."

The payoff table is presented below. 

|                | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -x$   | $A\rightarrow -w$  |
|                |  $B\rightarrow -x$   | $B\rightarrow -y$  |
|                |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -y$   | $A\rightarrow -z$  |
|                |  $B\rightarrow -w$   | $B\rightarrow -z$  |

**However, this is only a *Prisoner's Dilemma GAME* for A GIVEN RELATION between the years in prison (payoffs) as to be studied next.**

ps. Text adapted from [Wikipedia](https://en.wikipedia.org/wiki/Prisoner's_dilemma).

**(1) Consider the Prisoner's dilemma description given above.**

**(a) What is the relation between the payoffs values $x\geq 0$, $y\geq 0$, $w\geq 0$ and $z \geq 0$ so that the game can be classified as [Prisoner's Dilemma](https://en.wikipedia.org/wiki/Prisoner's_dilemma)?**

**(b) Verify the results (i.e., the proposed inequality) with numerical examples using [nashpy](https://nashpy.readthedocs.io/en/stable/index.html). Please provide one example when the inequality holds and one it does not (check my example for Dove and Hawyk game).**

*a)* To be Prisoner's Dilemma:
- Both being silent is better than both betraying each other, therefore:  -x > -z,
- Betraying other while other remain silent is likely the most suitable scenario so -y > -w,
- Nash equilibria happens when one betrays and other remain silent. So based on this perspective,  
-z > -w and  -y > -x. 

Putting all together: -y > -x > -z > -w

**b)** Lets test the results with nashpy

|                | $B$ cooperates  | $B$ not-cooperating     |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -2$   | $A \rightarrow 0$  |
|                |  $B \rightarrow -2$   | $B\rightarrow -6$  |
|                |                 |               |
| $A$ not-cooperating |  $A\rightarrow -6$      | $A\rightarrow -4$  |
|                |  $B\rightarrow 0$   | $B\rightarrow -4$  |


#### Test 1 
$$
A =
\begin{pmatrix}
    -2 & 0\\
    -6 & -4
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -2 & -6\\
    0 & -4
\end{pmatrix}
$$

#### Test 2
$$
A =
\begin{pmatrix}
    -1 & -2\\
    0 & -3
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -1 & 0\\
    -2 & -3
\end{pmatrix}
$$


In [6]:
import numpy as np
import nashpy as nash

#Test 1
A = [[-2, 0], [-6, -4]]
B = [[-2, -6], [0, -4]]

print("Test 1: Prison dilemma")
prison_dilemma = nash.Game(A, B)
display(prison_dilemma)

eqs = prison_dilemma.support_enumeration()
display(list(eqs))

print("Test 2: Prison dilemma")
A = [[-1, -2], [0, -3]]
B = [[-1, 0], [-2, -3]]

prison_dilemma = nash.Game(A, B)
display(prison_dilemma)

eqs = prison_dilemma.support_enumeration()
display(list(eqs))



Test 1: Prison dilemma


Bi matrix game with payoff matrices:

Row player:
[[-2  0]
 [-6 -4]]

Column player:
[[-2 -6]
 [ 0 -4]]

[(array([1., 0.]), array([1., 0.]))]

Test 2: Prison dilemma


Bi matrix game with payoff matrices:

Row player:
[[-1 -2]
 [ 0 -3]]

Column player:
[[-1  0]
 [-2 -3]]

[(array([1., 0.]), array([0., 1.])),
 (array([0., 1.]), array([1., 0.])),
 (array([0.5, 0.5]), array([0.5, 0.5]))]

In test 1 output reads as follows: the probability will be $1$ if A and B cooperates and the probability will be $0$ if both betrays.

In test 2 output reads as follows: 

 - **First line**: A cooperates with probability $1$ and betrays with probability $0$ while B cooperates with probabilty $0$ and betrays with probability $0$.
 - **Second line**: A cooperates with probability $0$ and betrays with probability $1$ while B cooperates with probability $1$ and betrays with probability $0$.
 - **Thrid line**: A and B cooperates with probability $1/2$ and both betrays with probability $1/2$.

**(2) Justify why the game from the previous exercise is or is not a good (reasonable) model when $A$ and $B$ are:**

**1. Two trained members from the army when they are in prison.**


**2. Competitive companies in the market discussing standardization.**


**3. Two different autonomous IoT-based home energy management algorithms that are focus on energy efficiency.**


**4. Two different autonomous IoT-based home energy management algorithms that are focus on profit maximization.**

**ps. You need to think about the assumption used in Game Theory and in the Prisoner's dilemma problem setting.**

Answer:

1. It might be reasonable model because betraying other he will get the shortest sentence or the second longest. If cooperating then he will get second longest sentence or longest sentence. However, two trained members might be loyal to each other so they might have communicate with each other before entering the prison dilemma. 

2. It is not good model for them because they likely cooperate with each other for getting one standard. However, another one might betray that leads to two standards. 

3. It is not good model because they have the same goal to achieve and no one can get more energy efficient on cost of another. So they prioritize to optimize the energy efficiency. 

4. It might not be a good model because the algorithms they use for maximization is based on predefined rules and optimization. 